#This dokcer compose file spins up both flask backend & react frontend apps together 
#Author - Sujin Nihar
#Date: 1st November 2021
version: '2.2'
services:
    server:
        build: ./flask
        ports:
         - "80:5000"
        volumes:
         - ./flask:/app
        environment:
         FLASK_ENV: development
    web:
        build: ./client/my-app
        ports:
         - "3000:3000"
        volumes:
         - ./client/my-app:/usr/src/app
        depends_on:
         - server
        



